# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='emoji',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
