# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='flag',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
