# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=1000)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
                ('emoji', models.CharField(default='', max_length=20)),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=140)),
                ('url_name', models.CharField(max_length=200)),
                ('description_long', models.CharField(default='', max_length=500)),
                ('description_short', models.CharField(default='', max_length=140)),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField()),
                ('bucksamonth', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('emoji', models.CharField(default='', max_length=20)),
                ('twitter', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_nickname', models.CharField(max_length=10)),
                ('bucksamonth', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_user', to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewed_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Service'),
        ),
    ]
