# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_subscription_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='date_created',
        ),
    ]
