# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 01:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_subscription_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
