# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_subscription_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_service', to='services.Service'),
        ),
    ]
