# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_emoji'),
        ('services', '0007_auto_20170325_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_interest_name', to='services.Interest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_interest', to='services.Service')),
            ],
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_name', to='services.Interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interest', to='accounts.UserProfile')),
            ],
        ),
    ]
