# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170327_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='serviceinterest',
            name='service',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
        migrations.DeleteModel(
            name='ServiceInterest',
        ),
        migrations.DeleteModel(
            name='UserInterest',
        ),
    ]
