# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170327_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
