# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
