# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20170420_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
