# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20170420_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
