# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20170423_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(blank=True),
        ),
    ]
