# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_service_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='cc_nickname',
            field=models.CharField(default='', max_length=10),
        ),
    ]
