# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='setup',
            field=models.BooleanField(default=False),
        ),
    ]
