# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
