# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-28 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170426_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(related_name='_userprofile_followers_+', to='accounts.UserProfile'),
        ),
    ]
