# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20170501_2021'),
        ('blog', '0005_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='post_service', to='services.Service'),
        ),
    ]
