# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-30 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={'ordering': ('-date',)},
        ),
    ]
